# Generated by Django 5.2 on 2025-05-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='creaqted_date',
            new_name='created_date',
        ),
    ]
