# Generated by Django 5.2 on 2025-05-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_creaqted_date_variation_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={},
        ),
    ]
